///usr/bin/env jbang "$0" "$@" ; exit $?
//JAVA 17+
//SOURCES EntityProcessor.java
//SOURCES JsonSerializer.java
//SOURCES DatabaseMapper.java

import java.lang.annotation.*;

// Annotation to mark entities
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@interface Entity {
    String table() default "";
}

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@interface Column {
    String name() default "";
}

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@interface Id {
}

// Example entity - in a real framework, processor would generate the mapper
@Entity(table = "users")
class User {
    @Id
    @Column(name = "id")
    private Long id;
    
    @Column(name = "name")
    private String name;
    
    @Column(name = "email")
    private String email;
    
    // Constructors
    public User() {}
    
    public User(Long id, String name, String email) {
        this.id = id;
        this.name = name;
        this.email = email;
    }
    
    // Getters and setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
}

// Generated mapper (normally auto-generated by annotation processor)
class UserMapper {
    // JSON serialization - NO REFLECTION!
    public static String toJson(User user) {
        StringBuilder json = new StringBuilder("{");
        json.append("\"id\":").append(user.getId()).append(",");
        json.append("\"name\":\"").append(escape(user.getName())).append("\",");
        json.append("\"email\":\"").append(escape(user.getEmail())).append("\"");
        json.append("}");
        return json.toString();
    }
    
    // JSON deserialization - NO REFLECTION!
    public static User fromJson(String json) {
        User user = new User();
        // Simple parser (in reality, use a proper JSON parser)
        String content = json.substring(1, json.length() - 1);
        String[] pairs = content.split(",");
        
        for (String pair : pairs) {
            String[] kv = pair.split(":", 2);
            String key = kv[0].replaceAll("\"", "").trim();
            String value = kv[1].replaceAll("\"", "").trim();
            
            switch (key) {
                case "id" -> user.setId(Long.parseLong(value));
                case "name" -> user.setName(value);
                case "email" -> user.setEmail(value);
            }
        }
        return user;
    }
    
    // SQL generation - NO REFLECTION!
    public static String toInsertSQL(User user) {
        return String.format(
            "INSERT INTO users (id, name, email) VALUES (%d, '%s', '%s')",
            user.getId(), 
            escape(user.getName()), 
            escape(user.getEmail())
        );
    }
    
    public static String toSelectSQL(Long id) {
        return "SELECT id, name, email FROM users WHERE id = " + id;
    }
    
    // Helper method
    private static String escape(String str) {
        if (str == null) return "";
        return str.replace("\"", "\\\"")
                  .replace("\n", "\\n")
                  .replace("\r", "\\r");
    }
}

public class framework_demo {
    public static void main(String[] args) {
        System.out.println("=== Reflection-Free Framework Demo ===\n");
        
        // Create entity
        User user = new User(1L, "John Doe", "john@example.com");
        
        // JSON serialization (no reflection!)
        String json = UserMapper.toJson(user);
        System.out.println("JSON Output:");
        System.out.println(json);
        
        // JSON deserialization (no reflection!)
        User fromJson = UserMapper.fromJson(json);
        System.out.println("\nDeserialized User:");
        System.out.println("ID: " + fromJson.getId());
        System.out.println("Name: " + fromJson.getName());
        System.out.println("Email: " + fromJson.getEmail());
        
        // SQL generation (no reflection!)
        System.out.println("\nGenerated SQL:");
        System.out.println(UserMapper.toInsertSQL(user));
        System.out.println(UserMapper.toSelectSQL(1L));
        
        System.out.println("\n✅ All operations completed without reflection!");
        System.out.println("✅ Ready for native image compilation!");
        
        // Show how annotation processing works
        EntityProcessor.generateMapperExample();
        System.out.println(JsonSerializer.example());
        System.out.println(DatabaseMapper.example());
    }
}
